version: "3.9"
services:
  web_api:
    build: backend
    container_name: employees_api
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
      - MSSQL_PID=Express